classDiagram
    Pipeline --o Pipeline Step
    Dataset Schema Constructor -- Polars Schema Constructor: Calls
    Dataset Schema Constructor -- Schema: Constructs
    Dataset -- Dataset Schema Constructor: Calls
    Pipeline Step -- Criteria
    project.Project -- Pipeline
    project.Project -- Dataset
    Criteria -- ColumnDescription
    ColumnDescription -- Schema
    Dataset -- Schema: Has Schema
    Pipeline -- Schema: References

    namespace logistics {
        class project.Project {
            +pipeline_output_directory
            +dataset
            +backend
            +optimize_for
            +file_manager
            +build_prototype()
        }

        class project.FileManager {
            +pipeline_directory
            +project_name
            +
        }

    }

    namespace expert_system {
        class Dataset{
            +dataframe
            +api
            +schema
            +build_schema()
        }

        class Dataset Schema Constructor{
            +backend
            -_setup_backend()
            +mean()
        }

        class Polars Schema Constructor {
            -_filter()
            -_make_column()
            +mean()
            +median()
            +type()
            +statistical_type()
            +nulls_percent()
            +train_test()
            +write_parquet()
            +read_parquet()
            +read_csv()
        }
        class Criteria {
            +test_column()
            +create_pipeline_step()
            +
        }
        class Schema
        class ColumnDescription {
            +
        }
    }
    
    namespace code_writing {
        class Pipeline{
            +pipeline_steps
            +write()
            +construct()
            ~\_\_repr__()
            ~\_\_getitem__()
        }

        class Pipeline Step{
            -import
            -name
            -definition
            -step_code
            +write_step()
            +__init__()
        }
    }